# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/rodri/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-13856-DESKTOP-ARKS4GD/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/Facultad/Digital_1/TPFinal_D1/Voltimetro_JCR/Voltimetro_JCR.cache/wt [current_project]
set_property parent.project_path Z:/Facultad/Digital_1/TPFinal_D1/Voltimetro_JCR/Voltimetro_JCR.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo z:/Facultad/Digital_1/TPFinal_D1/Voltimetro_JCR/Voltimetro_JCR.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  Z:/Facultad/Digital_1/TPFinal_D1/codes/ADC_sd.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/reg_Nb.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/sum_1b.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/sum_Nb.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/comp_Nb.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/BCD_counter.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/ROM.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/cHor.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/ffd.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/cVer.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/VGA.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/utils.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/cOnes.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/c33k.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/mux.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/Voltimetro.vhd
  Z:/Facultad/Digital_1/TPFinal_D1/codes/Voltimetro_Esquema_Arty_A7-35_top_level.vhd
}
read_ip -quiet Z:/Facultad/Digital_1/TPFinal_D1/Voltimetro_JCR/Voltimetro_JCR.srcs/sources_1/ip/clk_generator/clk_generator.xci
set_property used_in_implementation false [get_files -all z:/Facultad/Digital_1/TPFinal_D1/Voltimetro_JCR/Voltimetro_JCR.srcs/sources_1/ip/clk_generator/clk_generator_board.xdc]
set_property used_in_implementation false [get_files -all z:/Facultad/Digital_1/TPFinal_D1/Voltimetro_JCR/Voltimetro_JCR.srcs/sources_1/ip/clk_generator/clk_generator.xdc]
set_property used_in_implementation false [get_files -all z:/Facultad/Digital_1/TPFinal_D1/Voltimetro_JCR/Voltimetro_JCR.srcs/sources_1/ip/clk_generator/clk_generator_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Voltimetro_toplevel -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Voltimetro_toplevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Voltimetro_toplevel_utilization_synth.rpt -pb Voltimetro_toplevel_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
